### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pariberi** [AKSW/LiveRdfNews#5]
hello,
i faced with this error when building the project.
could anybody help me how it fixes?
![build error](https://cloud.githubusercontent.com/assets/20786693/17317234/a9799ecc-5890-11e6-88af-6baabf99e98d.png)

**Comment by LorenzBuehmann** [comment]
Your Maven command is wrong. Your call is something like 
`mvn install:install-file .... mvn -Dmaven.test.skip install`

I don't know what you want to achieve, but `mvn` is not a Maven goal. It looks more like you want to make two separate calls:
```
mvn install:install-file .... 
mvn -Dmaven.test.skip install
```
